
CREATE TABLE [dbo].[Customers](
    [CustomerId] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [Name] NVARCHAR(150) NOT NULL,
    [Email] NVARCHAR(150) NOT NULL
    [CreatedOn] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
